package com.roadnet.entity;

public enum NotificationType {
    INTRODUCTION_RECEIVED, INTRODUCTION_ACCEPTED, INTRODUCTION_DECLINED,
    CONNECTION_NEW, MOMENT_COMMENT, MOMENT_REACTION,
    BOOKING_RECEIVED, BOOKING_CONFIRMED, BOOKING_CANCELLED,
    PAYMENT_STATUS, VERIFICATION_UPDATE, SAFETY_ALERT, SYSTEM
}
