spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/roadnet_dev
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.roadnet: DEBUG
    org.hibernate.SQL: DEBUG
